INSERT INTO Shop VALUES ('AKS001', 'GANESHA POOJA STORE', 1)

INSERT INTO Shop VALUES ('AKS002', 'GAUTHAM ELECTRONICS', 1)

INSERT INTO Shop VALUES ('AKS003', 'VIKRAM FURNITURE AND APPLIANCES', 2)

INSERT INTO Shop VALUES ('AKS004', 'SIDDHARTHA BAGS AND SUITCASES', 2)

INSERT INTO Shop VALUES ('AKS005', 'SHEETHAL BEAUTY AND COSMETICS', 3)

INSERT INTO Shop VALUES ('AKS006', 'ANJALI FASHIONS', 3)

INSERT INTO Shop VALUES ('AKS007', 'SANJEEV HEALTHCARE', 3)